### ISSUE TITLE
Crash on onPrivateSub callback for private channel subscription.  

### ISSUE THREAD

**Issue by mussa-ibragimov** [centrifugal/centrifuge-mobile#8]
```
E/Go: panic: runtime error: invalid memory address or nil pointer dereference
E/Go: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b5997b1]
E/Go: goroutine 17 [running, locked to thread]:
E/Go: panic(0x8b7d9de0, 0x60ee6010)
E/Go: 	/Users/fz/go1.7/src/runtime/panic.go:500 +0x384
E/Go: golang.org/x/mobile/bind/seq.(*Ref).Get(0x0, 0x0, 0x0)
E/Go: 	/Users/fz/go/src/golang.org/x/mobile/bind/seq/ref.go:113 +0x21
E/Go: _/var/folders/gr/067g1z0d0pv1f37zm8l3mzhw0000gn/T/gomobile-work-907512447/gomobile_bind.(*proxycentrifuge_PrivateSubHandler).OnPrivateSub(0x60eea044, 0x60fa2000, 0x60f83a30, 0x1, 0x0, 0x0)
E/Go: 	/var/folders/gr/067g1z0d0pv1f37zm8l3mzhw0000gn/T/gomobile-work-907512447/gomobile_bind/go_centrifugemain.go:1157 +0xe1
E/Go: github.com/centrifugal/centrifuge-mobile.(*Client).privateSign(0x60fa2000, 0x60f2a4b0, 0x21, 0x60f584c0, 0x0, 0x0)
E/Go: 	/Users/fz/go/src/github.com/centrifugal/centrifuge-mobile/client.go:815 +0x193
E/Go: github.com/centrifugal/centrifuge-mobile.(*Sub).resubscribe(0x60f5a140, 0x0, 0x0)
E/Go: 	/Users/fz/go/src/github.com/centrifugal/centrifuge-mobile/sub.go:315 +0x1d8
E/Go: github.com/centrifugal/centrifuge-mobile.(*Client).Subscribe(0x60fa2000, 0x60f2a4b0, 0x21, 0x60f2a480, 0x1, 0x0, 0x0)
E/Go: 	/Users/fz/go/src/github.com/centrifugal/centrifuge-mobile/client.go:839 +0x147
E/Go: _/var/folders/gr/067g1z0d0pv1f37zm8l3mzhw0000gn/T/gomobile-work-907512447/gomobile_bind.proxycentrifuge_Client_Subscribe(0xffffffe5, 0xa36f3810, 0x21, 0xffffffe3, 0x8b552c4c, 0x60fc1f30)
E/Go: 	/var/folders/gr/067g1z0d0pv1f37zm8l3mzhw0000gn/T/gomobile-work-907512447/gomobile_bind/go_centrifugemain.go:63 +0xd1
E/Go: _/var/folders/gr/067g1z0d0pv1f37zm8l3mzhw0000gn/T/gomobile-work-907512447/gomobile_bind._cgoexpwrap_87fcc104c08b_proxycentrifuge_Client_Subscribe(0xffffffe5, 0xa36f3810, 0x21, 0xffffffe3, 0xadc88cc4, 0xbfb38eb4)
E/Go: 	??:0 +0x33
```
I get this error while trying to subscribe to private channel:

```
    @Override
    public PrivateSign onPrivateSub(Client client, PrivateRequest privateRequest) throws Exception {
        Loggi.d("onPrivateSub");
        String clientId = privateRequest.getClientID();
        String channel = privateRequest.getChannel();
        PrivateSignCredentials privateSignCredentials = getPrivateSignCredentials(clientId, channel);

        PrivateSign privateSign = new PrivateSign();
        privateSign.setInfo(privateSignCredentials.getInfo());
        privateSign.setSign(privateSignCredentials.getSign());

        return privateSign;
    }
```

For some reason, I cannot make `getPrivateSignCredentials` request to my server. I know this method does work. It only happens in `onPrivateSub` callback method.

`PrivateSignCredentials` is my local class to store data for `PrivateSign`.

--

I've found out that if connection was instantiated in "main thread" the `onPrivateSub` callback runs on the same thread. However, error still happens even if I instantiate connection in "worker thread".

**Comment by FZambia** [comment]
Hi! Thanks for report! 

Couple of questions to help investigating:

1) Is this crash reproduces every time?
2) What is `Credentials` - is this `Credentials` from this package - i.e. [this](https://godoc.org/github.com/centrifugal/centrifuge-mobile#Credentials) or your own object? Because those Credentials are not related to private sign requesting.
2) Are you sure that crash happens in a moment when you call `new PrivateSign ()`? Can you try with extra log line after `new PrivateSign ()` - because it seems strange for me that this call  is the reason of crash - I suppose that crash happens later after return from `onPrivateSub` function.

**Comment by mussa-ibragimov** [comment]
Hi, thanks for your reply. I've updated the initial text.

1) yes.
2) It's my class.
3) It was wrong statement. See updated text above.
